<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/audience/team_list.proto

namespace Xsuportal\Proto\Services\Audience;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xsuportal.proto.services.audience.ListTeamsResponse</code>
 */
class ListTeamsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.services.audience.ListTeamsResponse.TeamListItem teams = 1;</code>
     */
    private $teams;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xsuportal\Proto\Services\Audience\ListTeamsResponse\TeamListItem[]|\Google\Protobuf\Internal\RepeatedField $teams
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xsuportal\Services\Audience\TeamList::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.services.audience.ListTeamsResponse.TeamListItem teams = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTeams()
    {
        return $this->teams;
    }

    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.services.audience.ListTeamsResponse.TeamListItem teams = 1;</code>
     * @param \Xsuportal\Proto\Services\Audience\ListTeamsResponse\TeamListItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTeams($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xsuportal\Proto\Services\Audience\ListTeamsResponse\TeamListItem::class);
        $this->teams = $arr;

        return $this;
    }

}

