<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/resources/notification.proto

namespace Xsuportal\Proto\Resources\Notification;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xsuportal.proto.resources.Notification.TestMessage</code>
 */
class TestMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 something = 1;</code>
     */
    private $something = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $something
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xsuportal\Resources\Notification::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 something = 1;</code>
     * @return int|string
     */
    public function getSomething()
    {
        return $this->something;
    }

    /**
     * Generated from protobuf field <code>int64 something = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSomething($var)
    {
        GPBUtil::checkInt64($var);
        $this->something = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(TestMessage::class, \Xsuportal\Proto\Resources\Notification_TestMessage::class);

