<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/contestant/clarifications.proto

namespace GPBMetadata\Xsuportal\Services\Contestant;

class Clarifications
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Xsuportal\Resources\Clarification::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac6030a32787375706f7274616c2f73657276696365732f636f6e746573" .
            "74616e742f636c6172696669636174696f6e732e70726f746f1223787375" .
            "706f7274616c2e70726f746f2e73657276696365732e636f6e7465737461" .
            "6e74221b0a194c697374436c6172696669636174696f6e73526571756573" .
            "74225e0a1a4c697374436c6172696669636174696f6e73526573706f6e73" .
            "6512400a0e636c6172696669636174696f6e7318012003280b32282e7873" .
            "75706f7274616c2e70726f746f2e7265736f75726365732e436c61726966" .
            "69636174696f6e222f0a1b52657175657374436c6172696669636174696f" .
            "6e5265717565737412100a087175657374696f6e180120012809225f0a1c" .
            "52657175657374436c6172696669636174696f6e526573706f6e7365123f" .
            "0a0d636c6172696669636174696f6e18012001280b32282e787375706f72" .
            "74616c2e70726f746f2e7265736f75726365732e436c6172696669636174" .
            "696f6e42545a526769746875622e636f6d2f697375636f6e2f697375636f" .
            "6e31302d66696e616c2f7765626170702f676f6c616e672f70726f746f2f" .
            "787375706f7274616c2f73657276696365732f636f6e74657374616e7462" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

