<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/contestant/dashboard.proto

namespace GPBMetadata\Xsuportal\Services\Contestant;

class Dashboard
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Xsuportal\Resources\Leaderboard::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a98020a2d787375706f7274616c2f73657276696365732f636f6e746573" .
            "74616e742f64617368626f6172642e70726f746f1223787375706f727461" .
            "6c2e70726f746f2e73657276696365732e636f6e74657374616e7422120a" .
            "1044617368626f6172645265717565737422500a1144617368626f617264" .
            "526573706f6e7365123b0a0b6c6561646572626f61726418012001280b32" .
            "262e787375706f7274616c2e70726f746f2e7265736f75726365732e4c65" .
            "61646572626f61726442545a526769746875622e636f6d2f697375636f6e" .
            "2f697375636f6e31302d66696e616c2f7765626170702f676f6c616e672f" .
            "70726f746f2f787375706f7274616c2f73657276696365732f636f6e7465" .
            "7374616e74620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

