<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/registration/create_team.proto

namespace Xsuportal\Proto\Services\Registration;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xsuportal.proto.services.registration.CreateTeamResponse</code>
 */
class CreateTeamResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 team_id = 1;</code>
     */
    private $team_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $team_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xsuportal\Services\Registration\CreateTeam::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 team_id = 1;</code>
     * @return int|string
     */
    public function getTeamId()
    {
        return $this->team_id;
    }

    /**
     * Generated from protobuf field <code>int64 team_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTeamId($var)
    {
        GPBUtil::checkInt64($var);
        $this->team_id = $var;

        return $this;
    }

}

