# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/admin/initialize.proto

require 'google/protobuf'

require 'xsuportal/resources/contest_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("xsuportal/services/admin/initialize.proto", :syntax => :proto3) do
    add_message "xsuportal.proto.services.admin.InitializeRequest" do
      optional :contest, :message, 1, "xsuportal.proto.resources.Contest"
    end
    add_message "xsuportal.proto.services.admin.InitializeResponse" do
      optional :language, :string, 1
      optional :benchmark_server, :message, 2, "xsuportal.proto.services.admin.InitializeResponse.BenchmarkServer"
    end
    add_message "xsuportal.proto.services.admin.InitializeResponse.BenchmarkServer" do
      optional :host, :string, 1
      optional :port, :int64, 2
    end
  end
end

module Xsuportal
  module Proto
    module Services
      module Admin
        InitializeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.services.admin.InitializeRequest").msgclass
        InitializeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.services.admin.InitializeResponse").msgclass
        InitializeResponse::BenchmarkServer = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.services.admin.InitializeResponse.BenchmarkServer").msgclass
      end
    end
  end
end
