# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/admin/teams.proto

require 'google/protobuf'

require 'xsuportal/resources/team_pb'
require 'xsuportal/resources/contestant_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("xsuportal/services/admin/teams.proto", :syntax => :proto3) do
    add_message "xsuportal.proto.services.admin.ListTeamsRequest" do
    end
    add_message "xsuportal.proto.services.admin.ListTeamsResponse" do
      repeated :teams, :message, 1, "xsuportal.proto.services.admin.ListTeamsResponse.TeamListItem"
    end
    add_message "xsuportal.proto.services.admin.ListTeamsResponse.TeamListItem" do
      optional :team_id, :int64, 1
      optional :name, :string, 2
      repeated :member_names, :string, 3
      optional :is_student, :bool, 5
      optional :withdrawn, :bool, 6
    end
    add_message "xsuportal.proto.services.admin.GetTeamRequest" do
      optional :id, :int64, 1
    end
    add_message "xsuportal.proto.services.admin.GetTeamResponse" do
      optional :team, :message, 1, "xsuportal.proto.resources.Team"
    end
    add_message "xsuportal.proto.services.admin.UpdateTeamRequest" do
      optional :team, :message, 1, "xsuportal.proto.resources.Team"
      repeated :contestants, :message, 2, "xsuportal.proto.resources.Contestant"
    end
    add_message "xsuportal.proto.services.admin.UpdateTeamResponse" do
    end
  end
end

module Xsuportal
  module Proto
    module Services
      module Admin
        ListTeamsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.services.admin.ListTeamsRequest").msgclass
        ListTeamsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.services.admin.ListTeamsResponse").msgclass
        ListTeamsResponse::TeamListItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.services.admin.ListTeamsResponse.TeamListItem").msgclass
        GetTeamRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.services.admin.GetTeamRequest").msgclass
        GetTeamResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.services.admin.GetTeamResponse").msgclass
        UpdateTeamRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.services.admin.UpdateTeamRequest").msgclass
        UpdateTeamResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.services.admin.UpdateTeamResponse").msgclass
      end
    end
  end
end
