# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/dcim/instance_management.proto

require 'google/protobuf'

require 'xsuportal/resources/contestant_instance_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("xsuportal/services/dcim/instance_management.proto", :syntax => :proto3) do
    add_message "xsuportal.proto.services.dcim.InformInstanceStateUpdateRequest" do
      optional :token, :string, 1
      optional :instance, :message, 2, "xsuportal.proto.resources.ContestantInstance"
    end
    add_message "xsuportal.proto.services.dcim.InformInstanceStateUpdateResponse" do
    end
  end
end

module Xsuportal
  module Proto
    module Services
      module Dcim
        InformInstanceStateUpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.services.dcim.InformInstanceStateUpdateRequest").msgclass
        InformInstanceStateUpdateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.services.dcim.InformInstanceStateUpdateResponse").msgclass
      end
    end
  end
end
