<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/error.proto

namespace GPBMetadata\Xsuportal;

class Error
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae4020a15787375706f7274616c2f6572726f722e70726f746f120f7873" .
            "75706f7274616c2e70726f746f22ef010a054572726f72120c0a04636f64" .
            "65180120012805120c0a046e616d6518022001280912150a0d68756d616e" .
            "5f6d657373616765180320012809121a0a1268756d616e5f646573637269" .
            "7074696f6e7318042003280912340a0a64656275675f696e666f18102001" .
            "280b32202e787375706f7274616c2e70726f746f2e4572726f722e446562" .
            "7567496e666f1a610a094465627567496e666f12110a0965786365707469" .
            "6f6e180120012809120d0a05747261636518022003280912190a11617070" .
            "6c69636174696f6e5f747261636518032003280912170a0f6672616d6577" .
            "6f726b5f747261636518042003280942405a3e6769746875622e636f6d2f" .
            "697375636f6e2f697375636f6e31302d66696e616c2f7765626170702f67" .
            "6f6c616e672f70726f746f2f787375706f7274616c620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

