# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/resources/clarification.proto

require 'google/protobuf'

require 'xsuportal/resources/team_pb'
require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("xsuportal/resources/clarification.proto", :syntax => :proto3) do
    add_message "xsuportal.proto.resources.Clarification" do
      optional :id, :int64, 1
      optional :team_id, :int64, 2
      optional :answered, :bool, 3
      optional :disclosed, :bool, 4
      optional :question, :string, 5
      optional :answer, :string, 6
      optional :created_at, :message, 7, "google.protobuf.Timestamp"
      optional :answered_at, :message, 8, "google.protobuf.Timestamp"
      optional :team, :message, 16, "xsuportal.proto.resources.Team"
    end
  end
end

module Xsuportal
  module Proto
    module Resources
      Clarification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.resources.Clarification").msgclass
    end
  end
end
