# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/resources/contestant.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("xsuportal/resources/contestant.proto", :syntax => :proto3) do
    add_message "xsuportal.proto.resources.Contestant" do
      optional :id, :int64, 1
      optional :team_id, :int64, 2
      optional :name, :string, 3
      optional :contestant_detail, :message, 7, "xsuportal.proto.resources.Contestant.ContestantDetail"
    end
    add_message "xsuportal.proto.resources.Contestant.ContestantDetail" do
      optional :github_login, :string, 1
      optional :discord_tag, :string, 2
      optional :is_student, :bool, 3
      optional :avatar_url, :string, 4
    end
  end
end

module Xsuportal
  module Proto
    module Resources
      Contestant = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.resources.Contestant").msgclass
      Contestant::ContestantDetail = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.resources.Contestant.ContestantDetail").msgclass
    end
  end
end
