# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/resources/leaderboard.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'xsuportal/resources/team_pb'
require 'xsuportal/resources/contest_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("xsuportal/resources/leaderboard.proto", :syntax => :proto3) do
    add_message "xsuportal.proto.resources.Leaderboard" do
      repeated :teams, :message, 1, "xsuportal.proto.resources.Leaderboard.LeaderboardItem"
      repeated :general_teams, :message, 2, "xsuportal.proto.resources.Leaderboard.LeaderboardItem"
      repeated :student_teams, :message, 3, "xsuportal.proto.resources.Leaderboard.LeaderboardItem"
      repeated :progresses, :message, 4, "xsuportal.proto.resources.Leaderboard.LeaderboardItem"
      optional :contest, :message, 5, "xsuportal.proto.resources.Contest"
    end
    add_message "xsuportal.proto.resources.Leaderboard.LeaderboardItem" do
      repeated :scores, :message, 1, "xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore"
      optional :best_score, :message, 2, "xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore"
      optional :latest_score, :message, 3, "xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore"
      optional :finish_count, :int64, 4
      optional :team, :message, 16, "xsuportal.proto.resources.Team"
    end
    add_message "xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore" do
      optional :score, :int64, 1
      optional :started_at, :message, 2, "google.protobuf.Timestamp"
      optional :marked_at, :message, 3, "google.protobuf.Timestamp"
    end
  end
end

module Xsuportal
  module Proto
    module Resources
      Leaderboard = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.resources.Leaderboard").msgclass
      Leaderboard::LeaderboardItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.resources.Leaderboard.LeaderboardItem").msgclass
      Leaderboard::LeaderboardItem::LeaderboardScore = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore").msgclass
    end
  end
end
