# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/resources/notification.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("xsuportal/resources/notification.proto", :syntax => :proto3) do
    add_message "xsuportal.proto.resources.Notification" do
      optional :id, :int64, 1
      optional :created_at, :message, 2, "google.protobuf.Timestamp"
      oneof :content do
        optional :content_benchmark_job, :message, 3, "xsuportal.proto.resources.Notification.BenchmarkJobMessage"
        optional :content_clarification, :message, 4, "xsuportal.proto.resources.Notification.ClarificationMessage"
        optional :content_test, :message, 5, "xsuportal.proto.resources.Notification.TestMessage"
      end
    end
    add_message "xsuportal.proto.resources.Notification.BenchmarkJobMessage" do
      optional :benchmark_job_id, :int64, 1
    end
    add_message "xsuportal.proto.resources.Notification.ClarificationMessage" do
      optional :clarification_id, :int64, 1
      optional :owned, :bool, 2
      optional :updated, :bool, 3
    end
    add_message "xsuportal.proto.resources.Notification.TestMessage" do
      optional :something, :int64, 1
    end
  end
end

module Xsuportal
  module Proto
    module Resources
      Notification = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.resources.Notification").msgclass
      Notification::BenchmarkJobMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.resources.Notification.BenchmarkJobMessage").msgclass
      Notification::ClarificationMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.resources.Notification.ClarificationMessage").msgclass
      Notification::TestMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.resources.Notification.TestMessage").msgclass
    end
  end
end
