# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/resources/staff.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("xsuportal/resources/staff.proto", :syntax => :proto3) do
    add_message "xsuportal.proto.resources.Staff" do
      optional :id, :int64, 1
      optional :github_login, :string, 2
    end
  end
end

module Xsuportal
  module Proto
    module Resources
      Staff = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.resources.Staff").msgclass
    end
  end
end
