<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/contestant/login.proto

namespace GPBMetadata\Xsuportal\Services\Contestant;

class Login
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af8010a29787375706f7274616c2f73657276696365732f636f6e746573" .
            "74616e742f6c6f67696e2e70726f746f1223787375706f7274616c2e7072" .
            "6f746f2e73657276696365732e636f6e74657374616e7422370a0c4c6f67" .
            "696e5265717565737412150a0d636f6e74657374616e745f696418012001" .
            "280912100a0870617373776f7264180220012809220f0a0d4c6f67696e52" .
            "6573706f6e736542545a526769746875622e636f6d2f697375636f6e2f69" .
            "7375636f6e31302d66696e616c2f7765626170702f676f6c616e672f7072" .
            "6f746f2f787375706f7274616c2f73657276696365732f636f6e74657374" .
            "616e74620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

