<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/resources/leaderboard.proto

namespace Xsuportal\Proto\Resources\Leaderboard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xsuportal.proto.resources.Leaderboard.LeaderboardItem</code>
 */
class LeaderboardItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore scores = 1;</code>
     */
    private $scores;
    /**
     * Generated from protobuf field <code>.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore best_score = 2;</code>
     */
    private $best_score = null;
    /**
     * Generated from protobuf field <code>.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore latest_score = 3;</code>
     */
    private $latest_score = null;
    /**
     * Generated from protobuf field <code>int64 finish_count = 4;</code>
     */
    private $finish_count = 0;
    /**
     * Generated from protobuf field <code>.xsuportal.proto.resources.Team team = 16;</code>
     */
    private $team = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem\LeaderboardScore[]|\Google\Protobuf\Internal\RepeatedField $scores
     *     @type \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem\LeaderboardScore $best_score
     *     @type \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem\LeaderboardScore $latest_score
     *     @type int|string $finish_count
     *     @type \Xsuportal\Proto\Resources\Team $team
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xsuportal\Resources\Leaderboard::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore scores = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getScores()
    {
        return $this->scores;
    }

    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore scores = 1;</code>
     * @param \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem\LeaderboardScore[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setScores($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem\LeaderboardScore::class);
        $this->scores = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore best_score = 2;</code>
     * @return \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem\LeaderboardScore
     */
    public function getBestScore()
    {
        return $this->best_score;
    }

    /**
     * Generated from protobuf field <code>.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore best_score = 2;</code>
     * @param \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem\LeaderboardScore $var
     * @return $this
     */
    public function setBestScore($var)
    {
        GPBUtil::checkMessage($var, \Xsuportal\Proto\Resources\Leaderboard_LeaderboardItem_LeaderboardScore::class);
        $this->best_score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore latest_score = 3;</code>
     * @return \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem\LeaderboardScore
     */
    public function getLatestScore()
    {
        return $this->latest_score;
    }

    /**
     * Generated from protobuf field <code>.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore latest_score = 3;</code>
     * @param \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem\LeaderboardScore $var
     * @return $this
     */
    public function setLatestScore($var)
    {
        GPBUtil::checkMessage($var, \Xsuportal\Proto\Resources\Leaderboard_LeaderboardItem_LeaderboardScore::class);
        $this->latest_score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 finish_count = 4;</code>
     * @return int|string
     */
    public function getFinishCount()
    {
        return $this->finish_count;
    }

    /**
     * Generated from protobuf field <code>int64 finish_count = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFinishCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->finish_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xsuportal.proto.resources.Team team = 16;</code>
     * @return \Xsuportal\Proto\Resources\Team
     */
    public function getTeam()
    {
        return $this->team;
    }

    /**
     * Generated from protobuf field <code>.xsuportal.proto.resources.Team team = 16;</code>
     * @param \Xsuportal\Proto\Resources\Team $var
     * @return $this
     */
    public function setTeam($var)
    {
        GPBUtil::checkMessage($var, \Xsuportal\Proto\Resources\Team::class);
        $this->team = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(LeaderboardItem::class, \Xsuportal\Proto\Resources\Leaderboard_LeaderboardItem::class);

