<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/resources/contest.proto

namespace Xsuportal\Proto\Resources\Contest;

/**
 * Protobuf type <code>xsuportal.proto.resources.Contest.Status</code>
 */
class Status
{
    /**
     * Generated from protobuf enum <code>STANDBY = 0;</code>
     */
    const STANDBY = 0;
    /**
     * Generated from protobuf enum <code>REGISTRATION = 1;</code>
     */
    const REGISTRATION = 1;
    /**
     * Generated from protobuf enum <code>STARTED = 2;</code>
     */
    const STARTED = 2;
    /**
     * Generated from protobuf enum <code>FINISHED = 3;</code>
     */
    const FINISHED = 3;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Status::class, \Xsuportal\Proto\Resources\Contest_Status::class);

