// source: xsuportal/services/common/me.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var xsuportal_resources_team_pb = require('../../../xsuportal/resources/team_pb.js');
goog.object.extend(proto, xsuportal_resources_team_pb);
var xsuportal_resources_contestant_pb = require('../../../xsuportal/resources/contestant_pb.js');
goog.object.extend(proto, xsuportal_resources_contestant_pb);
var xsuportal_resources_contest_pb = require('../../../xsuportal/resources/contest_pb.js');
goog.object.extend(proto, xsuportal_resources_contest_pb);
goog.exportSymbol('proto.xsuportal.proto.services.common.GetCurrentSessionResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xsuportal.proto.services.common.GetCurrentSessionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.xsuportal.proto.services.common.GetCurrentSessionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.xsuportal.proto.services.common.GetCurrentSessionResponse.displayName = 'proto.xsuportal.proto.services.common.GetCurrentSessionResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xsuportal.proto.services.common.GetCurrentSessionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.xsuportal.proto.services.common.GetCurrentSessionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xsuportal.proto.services.common.GetCurrentSessionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xsuportal.proto.services.common.GetCurrentSessionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    team: (f = msg.getTeam()) && xsuportal_resources_team_pb.Team.toObject(includeInstance, f),
    contestant: (f = msg.getContestant()) && xsuportal_resources_contestant_pb.Contestant.toObject(includeInstance, f),
    contest: (f = msg.getContest()) && xsuportal_resources_contest_pb.Contest.toObject(includeInstance, f),
    pushVapidKey: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xsuportal.proto.services.common.GetCurrentSessionResponse}
 */
proto.xsuportal.proto.services.common.GetCurrentSessionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xsuportal.proto.services.common.GetCurrentSessionResponse;
  return proto.xsuportal.proto.services.common.GetCurrentSessionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xsuportal.proto.services.common.GetCurrentSessionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xsuportal.proto.services.common.GetCurrentSessionResponse}
 */
proto.xsuportal.proto.services.common.GetCurrentSessionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new xsuportal_resources_team_pb.Team;
      reader.readMessage(value,xsuportal_resources_team_pb.Team.deserializeBinaryFromReader);
      msg.setTeam(value);
      break;
    case 2:
      var value = new xsuportal_resources_contestant_pb.Contestant;
      reader.readMessage(value,xsuportal_resources_contestant_pb.Contestant.deserializeBinaryFromReader);
      msg.setContestant(value);
      break;
    case 4:
      var value = new xsuportal_resources_contest_pb.Contest;
      reader.readMessage(value,xsuportal_resources_contest_pb.Contest.deserializeBinaryFromReader);
      msg.setContest(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setPushVapidKey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xsuportal.proto.services.common.GetCurrentSessionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xsuportal.proto.services.common.GetCurrentSessionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xsuportal.proto.services.common.GetCurrentSessionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xsuportal.proto.services.common.GetCurrentSessionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTeam();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      xsuportal_resources_team_pb.Team.serializeBinaryToWriter
    );
  }
  f = message.getContestant();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      xsuportal_resources_contestant_pb.Contestant.serializeBinaryToWriter
    );
  }
  f = message.getContest();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      xsuportal_resources_contest_pb.Contest.serializeBinaryToWriter
    );
  }
  f = message.getPushVapidKey();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional xsuportal.proto.resources.Team team = 1;
 * @return {?proto.xsuportal.proto.resources.Team}
 */
proto.xsuportal.proto.services.common.GetCurrentSessionResponse.prototype.getTeam = function() {
  return /** @type{?proto.xsuportal.proto.resources.Team} */ (
    jspb.Message.getWrapperField(this, xsuportal_resources_team_pb.Team, 1));
};


/**
 * @param {?proto.xsuportal.proto.resources.Team|undefined} value
 * @return {!proto.xsuportal.proto.services.common.GetCurrentSessionResponse} returns this
*/
proto.xsuportal.proto.services.common.GetCurrentSessionResponse.prototype.setTeam = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.xsuportal.proto.services.common.GetCurrentSessionResponse} returns this
 */
proto.xsuportal.proto.services.common.GetCurrentSessionResponse.prototype.clearTeam = function() {
  return this.setTeam(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.xsuportal.proto.services.common.GetCurrentSessionResponse.prototype.hasTeam = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional xsuportal.proto.resources.Contestant contestant = 2;
 * @return {?proto.xsuportal.proto.resources.Contestant}
 */
proto.xsuportal.proto.services.common.GetCurrentSessionResponse.prototype.getContestant = function() {
  return /** @type{?proto.xsuportal.proto.resources.Contestant} */ (
    jspb.Message.getWrapperField(this, xsuportal_resources_contestant_pb.Contestant, 2));
};


/**
 * @param {?proto.xsuportal.proto.resources.Contestant|undefined} value
 * @return {!proto.xsuportal.proto.services.common.GetCurrentSessionResponse} returns this
*/
proto.xsuportal.proto.services.common.GetCurrentSessionResponse.prototype.setContestant = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.xsuportal.proto.services.common.GetCurrentSessionResponse} returns this
 */
proto.xsuportal.proto.services.common.GetCurrentSessionResponse.prototype.clearContestant = function() {
  return this.setContestant(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.xsuportal.proto.services.common.GetCurrentSessionResponse.prototype.hasContestant = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional xsuportal.proto.resources.Contest contest = 4;
 * @return {?proto.xsuportal.proto.resources.Contest}
 */
proto.xsuportal.proto.services.common.GetCurrentSessionResponse.prototype.getContest = function() {
  return /** @type{?proto.xsuportal.proto.resources.Contest} */ (
    jspb.Message.getWrapperField(this, xsuportal_resources_contest_pb.Contest, 4));
};


/**
 * @param {?proto.xsuportal.proto.resources.Contest|undefined} value
 * @return {!proto.xsuportal.proto.services.common.GetCurrentSessionResponse} returns this
*/
proto.xsuportal.proto.services.common.GetCurrentSessionResponse.prototype.setContest = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.xsuportal.proto.services.common.GetCurrentSessionResponse} returns this
 */
proto.xsuportal.proto.services.common.GetCurrentSessionResponse.prototype.clearContest = function() {
  return this.setContest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.xsuportal.proto.services.common.GetCurrentSessionResponse.prototype.hasContest = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string push_vapid_key = 6;
 * @return {string}
 */
proto.xsuportal.proto.services.common.GetCurrentSessionResponse.prototype.getPushVapidKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.xsuportal.proto.services.common.GetCurrentSessionResponse} returns this
 */
proto.xsuportal.proto.services.common.GetCurrentSessionResponse.prototype.setPushVapidKey = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


goog.object.extend(exports, proto.xsuportal.proto.services.common);
