<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/registration/session.proto

namespace Xsuportal\Proto\Services\Registration;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xsuportal.proto.services.registration.DeleteRegistrationRequest</code>
 */
class DeleteRegistrationRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xsuportal\Services\Registration\Session::initOnce();
        parent::__construct($data);
    }

}

