<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/registration/session.proto

namespace Xsuportal\Proto\Services\Registration;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * query parameter
 *
 * Generated from protobuf message <code>xsuportal.proto.services.registration.GetRegistrationSessionQuery</code>
 */
class GetRegistrationSessionQuery extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 team_id = 1;</code>
     */
    private $team_id = 0;
    /**
     * Generated from protobuf field <code>string invite_token = 2;</code>
     */
    private $invite_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $team_id
     *     @type string $invite_token
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xsuportal\Services\Registration\Session::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 team_id = 1;</code>
     * @return int|string
     */
    public function getTeamId()
    {
        return $this->team_id;
    }

    /**
     * Generated from protobuf field <code>int64 team_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTeamId($var)
    {
        GPBUtil::checkInt64($var);
        $this->team_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string invite_token = 2;</code>
     * @return string
     */
    public function getInviteToken()
    {
        return $this->invite_token;
    }

    /**
     * Generated from protobuf field <code>string invite_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setInviteToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->invite_token = $var;

        return $this;
    }

}

