<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/registration/session.proto

namespace Xsuportal\Proto\Services\Registration;

if (false) {
    /**
     * This class is deprecated. Use Xsuportal\Proto\Services\Registration\GetRegistrationSessionResponse\Status instead.
     * @deprecated
     */
    class GetRegistrationSessionResponse_Status {}
}
class_exists(GetRegistrationSessionResponse\Status::class);
@trigger_error('Xsuportal\Proto\Services\Registration\GetRegistrationSessionResponse_Status is deprecated and will be removed in the next major release. Use Xsuportal\Proto\Services\Registration\GetRegistrationSessionResponse\Status instead', E_USER_DEPRECATED);

