<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: service.proto

namespace App\Service;

use Spiral\GRPC;
use App\Service\Message;

interface ServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "app.Service";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Message\Message $in
    * @return Message\Message
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Welcome(GRPC\ContextInterface $ctx, Message\Message $in): Message\Message;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Message\Job $in
    * @return Message\JobID
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Schedule(GRPC\ContextInterface $ctx, Message\Job $in): Message\JobID;
}
