// source: xsuportal/resources/leaderboard.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var xsuportal_resources_team_pb = require('../../xsuportal/resources/team_pb.js');
goog.object.extend(proto, xsuportal_resources_team_pb);
var xsuportal_resources_contest_pb = require('../../xsuportal/resources/contest_pb.js');
goog.object.extend(proto, xsuportal_resources_contest_pb);
goog.exportSymbol('proto.xsuportal.proto.resources.Leaderboard', null, global);
goog.exportSymbol('proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem', null, global);
goog.exportSymbol('proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xsuportal.proto.resources.Leaderboard = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.xsuportal.proto.resources.Leaderboard.repeatedFields_, null);
};
goog.inherits(proto.xsuportal.proto.resources.Leaderboard, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.xsuportal.proto.resources.Leaderboard.displayName = 'proto.xsuportal.proto.resources.Leaderboard';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.repeatedFields_, null);
};
goog.inherits(proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.displayName = 'proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.displayName = 'proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.xsuportal.proto.resources.Leaderboard.repeatedFields_ = [1,2,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xsuportal.proto.resources.Leaderboard.prototype.toObject = function(opt_includeInstance) {
  return proto.xsuportal.proto.resources.Leaderboard.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xsuportal.proto.resources.Leaderboard} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xsuportal.proto.resources.Leaderboard.toObject = function(includeInstance, msg) {
  var f, obj = {
    teamsList: jspb.Message.toObjectList(msg.getTeamsList(),
    proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.toObject, includeInstance),
    generalTeamsList: jspb.Message.toObjectList(msg.getGeneralTeamsList(),
    proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.toObject, includeInstance),
    studentTeamsList: jspb.Message.toObjectList(msg.getStudentTeamsList(),
    proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.toObject, includeInstance),
    progressesList: jspb.Message.toObjectList(msg.getProgressesList(),
    proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.toObject, includeInstance),
    contest: (f = msg.getContest()) && xsuportal_resources_contest_pb.Contest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xsuportal.proto.resources.Leaderboard}
 */
proto.xsuportal.proto.resources.Leaderboard.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xsuportal.proto.resources.Leaderboard;
  return proto.xsuportal.proto.resources.Leaderboard.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xsuportal.proto.resources.Leaderboard} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xsuportal.proto.resources.Leaderboard}
 */
proto.xsuportal.proto.resources.Leaderboard.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem;
      reader.readMessage(value,proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.deserializeBinaryFromReader);
      msg.addTeams(value);
      break;
    case 2:
      var value = new proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem;
      reader.readMessage(value,proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.deserializeBinaryFromReader);
      msg.addGeneralTeams(value);
      break;
    case 3:
      var value = new proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem;
      reader.readMessage(value,proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.deserializeBinaryFromReader);
      msg.addStudentTeams(value);
      break;
    case 4:
      var value = new proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem;
      reader.readMessage(value,proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.deserializeBinaryFromReader);
      msg.addProgresses(value);
      break;
    case 5:
      var value = new xsuportal_resources_contest_pb.Contest;
      reader.readMessage(value,xsuportal_resources_contest_pb.Contest.deserializeBinaryFromReader);
      msg.setContest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xsuportal.proto.resources.Leaderboard.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xsuportal.proto.resources.Leaderboard.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xsuportal.proto.resources.Leaderboard} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xsuportal.proto.resources.Leaderboard.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTeamsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.serializeBinaryToWriter
    );
  }
  f = message.getGeneralTeamsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.serializeBinaryToWriter
    );
  }
  f = message.getStudentTeamsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.serializeBinaryToWriter
    );
  }
  f = message.getProgressesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.serializeBinaryToWriter
    );
  }
  f = message.getContest();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      xsuportal_resources_contest_pb.Contest.serializeBinaryToWriter
    );
  }
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.prototype.toObject = function(opt_includeInstance) {
  return proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    scoresList: jspb.Message.toObjectList(msg.getScoresList(),
    proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.toObject, includeInstance),
    bestScore: (f = msg.getBestScore()) && proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.toObject(includeInstance, f),
    latestScore: (f = msg.getLatestScore()) && proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.toObject(includeInstance, f),
    finishCount: jspb.Message.getFieldWithDefault(msg, 4, 0),
    team: (f = msg.getTeam()) && xsuportal_resources_team_pb.Team.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem;
  return proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore;
      reader.readMessage(value,proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.deserializeBinaryFromReader);
      msg.addScores(value);
      break;
    case 2:
      var value = new proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore;
      reader.readMessage(value,proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.deserializeBinaryFromReader);
      msg.setBestScore(value);
      break;
    case 3:
      var value = new proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore;
      reader.readMessage(value,proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.deserializeBinaryFromReader);
      msg.setLatestScore(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setFinishCount(value);
      break;
    case 16:
      var value = new xsuportal_resources_team_pb.Team;
      reader.readMessage(value,xsuportal_resources_team_pb.Team.deserializeBinaryFromReader);
      msg.setTeam(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getScoresList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.serializeBinaryToWriter
    );
  }
  f = message.getBestScore();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.serializeBinaryToWriter
    );
  }
  f = message.getLatestScore();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.serializeBinaryToWriter
    );
  }
  f = message.getFinishCount();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getTeam();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      xsuportal_resources_team_pb.Team.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.prototype.toObject = function(opt_includeInstance) {
  return proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.toObject = function(includeInstance, msg) {
  var f, obj = {
    score: jspb.Message.getFieldWithDefault(msg, 1, 0),
    startedAt: (f = msg.getStartedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    markedAt: (f = msg.getMarkedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore;
  return proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setScore(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setStartedAt(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setMarkedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getScore();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getStartedAt();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getMarkedAt();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 score = 1;
 * @return {number}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.prototype.getScore = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore} returns this
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.prototype.setScore = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp started_at = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.prototype.getStartedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore} returns this
*/
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.prototype.setStartedAt = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore} returns this
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.prototype.clearStartedAt = function() {
  return this.setStartedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.prototype.hasStartedAt = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp marked_at = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.prototype.getMarkedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore} returns this
*/
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.prototype.setMarkedAt = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore} returns this
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.prototype.clearMarkedAt = function() {
  return this.setMarkedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore.prototype.hasMarkedAt = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated LeaderboardScore scores = 1;
 * @return {!Array<!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore>}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.prototype.getScoresList = function() {
  return /** @type{!Array<!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore, 1));
};


/**
 * @param {!Array<!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore>} value
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem} returns this
*/
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.prototype.setScoresList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore=} opt_value
 * @param {number=} opt_index
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.prototype.addScores = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem} returns this
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.prototype.clearScoresList = function() {
  return this.setScoresList([]);
};


/**
 * optional LeaderboardScore best_score = 2;
 * @return {?proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.prototype.getBestScore = function() {
  return /** @type{?proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore} */ (
    jspb.Message.getWrapperField(this, proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore, 2));
};


/**
 * @param {?proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore|undefined} value
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem} returns this
*/
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.prototype.setBestScore = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem} returns this
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.prototype.clearBestScore = function() {
  return this.setBestScore(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.prototype.hasBestScore = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional LeaderboardScore latest_score = 3;
 * @return {?proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.prototype.getLatestScore = function() {
  return /** @type{?proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore} */ (
    jspb.Message.getWrapperField(this, proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore, 3));
};


/**
 * @param {?proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.LeaderboardScore|undefined} value
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem} returns this
*/
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.prototype.setLatestScore = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem} returns this
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.prototype.clearLatestScore = function() {
  return this.setLatestScore(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.prototype.hasLatestScore = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int64 finish_count = 4;
 * @return {number}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.prototype.getFinishCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem} returns this
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.prototype.setFinishCount = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional Team team = 16;
 * @return {?proto.xsuportal.proto.resources.Team}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.prototype.getTeam = function() {
  return /** @type{?proto.xsuportal.proto.resources.Team} */ (
    jspb.Message.getWrapperField(this, xsuportal_resources_team_pb.Team, 16));
};


/**
 * @param {?proto.xsuportal.proto.resources.Team|undefined} value
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem} returns this
*/
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.prototype.setTeam = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem} returns this
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.prototype.clearTeam = function() {
  return this.setTeam(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem.prototype.hasTeam = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * repeated LeaderboardItem teams = 1;
 * @return {!Array<!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem>}
 */
proto.xsuportal.proto.resources.Leaderboard.prototype.getTeamsList = function() {
  return /** @type{!Array<!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem, 1));
};


/**
 * @param {!Array<!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem>} value
 * @return {!proto.xsuportal.proto.resources.Leaderboard} returns this
*/
proto.xsuportal.proto.resources.Leaderboard.prototype.setTeamsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem}
 */
proto.xsuportal.proto.resources.Leaderboard.prototype.addTeams = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.xsuportal.proto.resources.Leaderboard} returns this
 */
proto.xsuportal.proto.resources.Leaderboard.prototype.clearTeamsList = function() {
  return this.setTeamsList([]);
};


/**
 * repeated LeaderboardItem general_teams = 2;
 * @return {!Array<!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem>}
 */
proto.xsuportal.proto.resources.Leaderboard.prototype.getGeneralTeamsList = function() {
  return /** @type{!Array<!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem, 2));
};


/**
 * @param {!Array<!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem>} value
 * @return {!proto.xsuportal.proto.resources.Leaderboard} returns this
*/
proto.xsuportal.proto.resources.Leaderboard.prototype.setGeneralTeamsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem}
 */
proto.xsuportal.proto.resources.Leaderboard.prototype.addGeneralTeams = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.xsuportal.proto.resources.Leaderboard} returns this
 */
proto.xsuportal.proto.resources.Leaderboard.prototype.clearGeneralTeamsList = function() {
  return this.setGeneralTeamsList([]);
};


/**
 * repeated LeaderboardItem student_teams = 3;
 * @return {!Array<!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem>}
 */
proto.xsuportal.proto.resources.Leaderboard.prototype.getStudentTeamsList = function() {
  return /** @type{!Array<!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem, 3));
};


/**
 * @param {!Array<!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem>} value
 * @return {!proto.xsuportal.proto.resources.Leaderboard} returns this
*/
proto.xsuportal.proto.resources.Leaderboard.prototype.setStudentTeamsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem}
 */
proto.xsuportal.proto.resources.Leaderboard.prototype.addStudentTeams = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.xsuportal.proto.resources.Leaderboard} returns this
 */
proto.xsuportal.proto.resources.Leaderboard.prototype.clearStudentTeamsList = function() {
  return this.setStudentTeamsList([]);
};


/**
 * repeated LeaderboardItem progresses = 4;
 * @return {!Array<!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem>}
 */
proto.xsuportal.proto.resources.Leaderboard.prototype.getProgressesList = function() {
  return /** @type{!Array<!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem, 4));
};


/**
 * @param {!Array<!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem>} value
 * @return {!proto.xsuportal.proto.resources.Leaderboard} returns this
*/
proto.xsuportal.proto.resources.Leaderboard.prototype.setProgressesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem}
 */
proto.xsuportal.proto.resources.Leaderboard.prototype.addProgresses = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.xsuportal.proto.resources.Leaderboard.LeaderboardItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.xsuportal.proto.resources.Leaderboard} returns this
 */
proto.xsuportal.proto.resources.Leaderboard.prototype.clearProgressesList = function() {
  return this.setProgressesList([]);
};


/**
 * optional Contest contest = 5;
 * @return {?proto.xsuportal.proto.resources.Contest}
 */
proto.xsuportal.proto.resources.Leaderboard.prototype.getContest = function() {
  return /** @type{?proto.xsuportal.proto.resources.Contest} */ (
    jspb.Message.getWrapperField(this, xsuportal_resources_contest_pb.Contest, 5));
};


/**
 * @param {?proto.xsuportal.proto.resources.Contest|undefined} value
 * @return {!proto.xsuportal.proto.resources.Leaderboard} returns this
*/
proto.xsuportal.proto.resources.Leaderboard.prototype.setContest = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.xsuportal.proto.resources.Leaderboard} returns this
 */
proto.xsuportal.proto.resources.Leaderboard.prototype.clearContest = function() {
  return this.setContest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.xsuportal.proto.resources.Leaderboard.prototype.hasContest = function() {
  return jspb.Message.getField(this, 5) != null;
};


goog.object.extend(exports, proto.xsuportal.proto.resources);
