<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/error.proto

namespace Xsuportal\Proto\Error;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xsuportal.proto.Error.DebugInfo</code>
 */
class DebugInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string exception = 1;</code>
     */
    private $exception = '';
    /**
     * Generated from protobuf field <code>repeated string trace = 2;</code>
     */
    private $trace;
    /**
     * Generated from protobuf field <code>repeated string application_trace = 3;</code>
     */
    private $application_trace;
    /**
     * Generated from protobuf field <code>repeated string framework_trace = 4;</code>
     */
    private $framework_trace;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $exception
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $trace
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $application_trace
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $framework_trace
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xsuportal\Error::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string exception = 1;</code>
     * @return string
     */
    public function getException()
    {
        return $this->exception;
    }

    /**
     * Generated from protobuf field <code>string exception = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setException($var)
    {
        GPBUtil::checkString($var, True);
        $this->exception = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string trace = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTrace()
    {
        return $this->trace;
    }

    /**
     * Generated from protobuf field <code>repeated string trace = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTrace($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->trace = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string application_trace = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getApplicationTrace()
    {
        return $this->application_trace;
    }

    /**
     * Generated from protobuf field <code>repeated string application_trace = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setApplicationTrace($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->application_trace = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string framework_trace = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFrameworkTrace()
    {
        return $this->framework_trace;
    }

    /**
     * Generated from protobuf field <code>repeated string framework_trace = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFrameworkTrace($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->framework_trace = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(DebugInfo::class, \Xsuportal\Proto\Error_DebugInfo::class);

