# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/error.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("xsuportal/error.proto", :syntax => :proto3) do
    add_message "xsuportal.proto.Error" do
      optional :code, :int32, 1
      optional :name, :string, 2
      optional :human_message, :string, 3
      repeated :human_descriptions, :string, 4
      optional :debug_info, :message, 16, "xsuportal.proto.Error.DebugInfo"
    end
    add_message "xsuportal.proto.Error.DebugInfo" do
      optional :exception, :string, 1
      repeated :trace, :string, 2
      repeated :application_trace, :string, 3
      repeated :framework_trace, :string, 4
    end
  end
end

module Xsuportal
  module Proto
    Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.Error").msgclass
    Error::DebugInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.Error.DebugInfo").msgclass
  end
end
