#!/usr/bin/env ruby
require 'optparse'
require 'json'
require 'mysql2'
require 'mysql2-cs-bind'

$: << File.expand_path('../ruby/lib', __dir__)
require 'xsuportal/resources/notification_pb'

def db
  @db ||= Mysql2::Client.new(
    host: ENV['MYSQL_HOSTNAME'] || '127.0.0.1',
    port: ENV['MYSQL_PORT'] || '3306',
    username: ENV['MYSQL_USER'] || 'isucon',
    database: ENV['MYSQL_DATABASE'] || 'xsuportal',
    password: ENV['MYSQL_PASS'] || 'isucon',
    charset: 'utf8mb4',
    database_timezone: :utc,
    cast_booleans: true,
    symbolize_keys: true,
    reconnect: true,
    init_command: "SET time_zone='+00:00';",
  )
end

contestant_id = nil
option_parser = OptionParser.new do |opt|
  opt.banner = "Usage: #{__FILE__} -c contestant_id"
  opt.on('-c contestant_id') {|x| contestant_id = x }
end
option_parser.parse!

abort option_parser.banner unless contestant_id

notifications = db.xquery(
  'SELECT * FROM `notifications` WHERE `contestant_id` = ? ORDER BY `id`',
  contestant_id,
)

notifications = notifications.map do |notification|
  notification.merge(Xsuportal::Proto::Resources::Notification.decode(notification[:encoded_message].unpack1('m0')).to_h)
end

puts notifications.to_json
