<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/admin/teams.proto

namespace Xsuportal\Proto\Services\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xsuportal.proto.services.admin.GetTeamResponse</code>
 */
class GetTeamResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.xsuportal.proto.resources.Team team = 1;</code>
     */
    private $team = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xsuportal\Proto\Resources\Team $team
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xsuportal\Services\Admin\Teams::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.xsuportal.proto.resources.Team team = 1;</code>
     * @return \Xsuportal\Proto\Resources\Team
     */
    public function getTeam()
    {
        return $this->team;
    }

    /**
     * Generated from protobuf field <code>.xsuportal.proto.resources.Team team = 1;</code>
     * @param \Xsuportal\Proto\Resources\Team $var
     * @return $this
     */
    public function setTeam($var)
    {
        GPBUtil::checkMessage($var, \Xsuportal\Proto\Resources\Team::class);
        $this->team = $var;

        return $this;
    }

}

