<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/admin/initialize.proto

namespace Xsuportal\Proto\Services\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xsuportal.proto.services.admin.InitializeResponse</code>
 */
class InitializeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * 実装言語
     *
     * Generated from protobuf field <code>string language = 1;</code>
     */
    private $language = '';
    /**
     * 実ベンチマーカーに伝える仮想ベンチマークサーバー(gRPC)のホスト情報
     *
     * Generated from protobuf field <code>.xsuportal.proto.services.admin.InitializeResponse.BenchmarkServer benchmark_server = 2;</code>
     */
    private $benchmark_server = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $language
     *           実装言語
     *     @type \Xsuportal\Proto\Services\Admin\InitializeResponse\BenchmarkServer $benchmark_server
     *           実ベンチマーカーに伝える仮想ベンチマークサーバー(gRPC)のホスト情報
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xsuportal\Services\Admin\Initialize::initOnce();
        parent::__construct($data);
    }

    /**
     * 実装言語
     *
     * Generated from protobuf field <code>string language = 1;</code>
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * 実装言語
     *
     * Generated from protobuf field <code>string language = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkString($var, True);
        $this->language = $var;

        return $this;
    }

    /**
     * 実ベンチマーカーに伝える仮想ベンチマークサーバー(gRPC)のホスト情報
     *
     * Generated from protobuf field <code>.xsuportal.proto.services.admin.InitializeResponse.BenchmarkServer benchmark_server = 2;</code>
     * @return \Xsuportal\Proto\Services\Admin\InitializeResponse\BenchmarkServer
     */
    public function getBenchmarkServer()
    {
        return $this->benchmark_server;
    }

    /**
     * 実ベンチマーカーに伝える仮想ベンチマークサーバー(gRPC)のホスト情報
     *
     * Generated from protobuf field <code>.xsuportal.proto.services.admin.InitializeResponse.BenchmarkServer benchmark_server = 2;</code>
     * @param \Xsuportal\Proto\Services\Admin\InitializeResponse\BenchmarkServer $var
     * @return $this
     */
    public function setBenchmarkServer($var)
    {
        GPBUtil::checkMessage($var, \Xsuportal\Proto\Services\Admin\InitializeResponse_BenchmarkServer::class);
        $this->benchmark_server = $var;

        return $this;
    }

}

