<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/admin/clarifications.proto

namespace Xsuportal\Proto\Services\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xsuportal.proto.services.admin.RespondClarificationRequest</code>
 */
class RespondClarificationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    private $id = 0;
    /**
     * Generated from protobuf field <code>bool disclose = 2;</code>
     */
    private $disclose = false;
    /**
     * Generated from protobuf field <code>string answer = 3;</code>
     */
    private $answer = '';
    /**
     * optional to override original question
     *
     * Generated from protobuf field <code>string question = 4;</code>
     */
    private $question = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type bool $disclose
     *     @type string $answer
     *     @type string $question
     *           optional to override original question
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xsuportal\Services\Admin\Clarifications::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool disclose = 2;</code>
     * @return bool
     */
    public function getDisclose()
    {
        return $this->disclose;
    }

    /**
     * Generated from protobuf field <code>bool disclose = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setDisclose($var)
    {
        GPBUtil::checkBool($var);
        $this->disclose = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string answer = 3;</code>
     * @return string
     */
    public function getAnswer()
    {
        return $this->answer;
    }

    /**
     * Generated from protobuf field <code>string answer = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAnswer($var)
    {
        GPBUtil::checkString($var, True);
        $this->answer = $var;

        return $this;
    }

    /**
     * optional to override original question
     *
     * Generated from protobuf field <code>string question = 4;</code>
     * @return string
     */
    public function getQuestion()
    {
        return $this->question;
    }

    /**
     * optional to override original question
     *
     * Generated from protobuf field <code>string question = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setQuestion($var)
    {
        GPBUtil::checkString($var, True);
        $this->question = $var;

        return $this;
    }

}

