<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/contestant/clarifications.proto

namespace Xsuportal\Proto\Services\Contestant;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xsuportal.proto.services.contestant.ListClarificationsRequest</code>
 */
class ListClarificationsRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xsuportal\Services\Contestant\Clarifications::initOnce();
        parent::__construct($data);
    }

}

