<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/contestant/notifications.proto

namespace Xsuportal\Proto\Services\Contestant;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xsuportal.proto.services.contestant.ListNotificationsResponse</code>
 */
class ListNotificationsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 last_answered_clarification_id = 1;</code>
     */
    private $last_answered_clarification_id = 0;
    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.resources.Notification notifications = 2;</code>
     */
    private $notifications;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $last_answered_clarification_id
     *     @type \Xsuportal\Proto\Resources\Notification[]|\Google\Protobuf\Internal\RepeatedField $notifications
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xsuportal\Services\Contestant\Notifications::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 last_answered_clarification_id = 1;</code>
     * @return int|string
     */
    public function getLastAnsweredClarificationId()
    {
        return $this->last_answered_clarification_id;
    }

    /**
     * Generated from protobuf field <code>int64 last_answered_clarification_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastAnsweredClarificationId($var)
    {
        GPBUtil::checkInt64($var);
        $this->last_answered_clarification_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.resources.Notification notifications = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNotifications()
    {
        return $this->notifications;
    }

    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.resources.Notification notifications = 2;</code>
     * @param \Xsuportal\Proto\Resources\Notification[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNotifications($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xsuportal\Proto\Resources\Notification::class);
        $this->notifications = $arr;

        return $this;
    }

}

