<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/contestant/notifications.proto

namespace Xsuportal\Proto\Services\Contestant;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xsuportal.proto.services.contestant.ListNotificationsQuery</code>
 */
class ListNotificationsQuery extends \Google\Protobuf\Internal\Message
{
    /**
     * Last notifications.id that a user-agent has received through
     * ListNotificationsQuery during a current session. If not specified (=0),
     * uses server-side `read` column as a hint.
     *
     * Generated from protobuf field <code>int64 after = 1;</code>
     */
    private $after = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $after
     *           Last notifications.id that a user-agent has received through
     *           ListNotificationsQuery during a current session. If not specified (=0),
     *           uses server-side `read` column as a hint.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xsuportal\Services\Contestant\Notifications::initOnce();
        parent::__construct($data);
    }

    /**
     * Last notifications.id that a user-agent has received through
     * ListNotificationsQuery during a current session. If not specified (=0),
     * uses server-side `read` column as a hint.
     *
     * Generated from protobuf field <code>int64 after = 1;</code>
     * @return int|string
     */
    public function getAfter()
    {
        return $this->after;
    }

    /**
     * Last notifications.id that a user-agent has received through
     * ListNotificationsQuery during a current session. If not specified (=0),
     * uses server-side `read` column as a hint.
     *
     * Generated from protobuf field <code>int64 after = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAfter($var)
    {
        GPBUtil::checkInt64($var);
        $this->after = $var;

        return $this;
    }

}

