<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/contestant/clarifications.proto

namespace Xsuportal\Proto\Services\Contestant;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xsuportal.proto.services.contestant.RequestClarificationRequest</code>
 */
class RequestClarificationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string question = 1;</code>
     */
    private $question = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $question
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xsuportal\Services\Contestant\Clarifications::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string question = 1;</code>
     * @return string
     */
    public function getQuestion()
    {
        return $this->question;
    }

    /**
     * Generated from protobuf field <code>string question = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setQuestion($var)
    {
        GPBUtil::checkString($var, True);
        $this->question = $var;

        return $this;
    }

}

