# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/account/login.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("xsuportal/services/account/login.proto", :syntax => :proto3) do
    add_message "xsuportal.proto.services.account.LoginRequest" do
      optional :contestant_id, :string, 1
      optional :password, :string, 2
    end
    add_message "xsuportal.proto.services.account.LoginResponse" do
      optional :status, :enum, 1, "xsuportal.proto.services.account.LoginResponse.Status"
      optional :error, :string, 2
    end
    add_enum "xsuportal.proto.services.account.LoginResponse.Status" do
      value :SUCCEEDED, 0
      value :FAILED, 1
    end
  end
end

module Xsuportal
  module Proto
    module Services
      module Account
        LoginRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.services.account.LoginRequest").msgclass
        LoginResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.services.account.LoginResponse").msgclass
        LoginResponse::Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xsuportal.proto.services.account.LoginResponse.Status").enummodule
      end
    end
  end
end
