<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/error.proto

namespace Xsuportal\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xsuportal.proto.Error</code>
 */
class Error extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 code = 1;</code>
     */
    private $code = 0;
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string human_message = 3;</code>
     */
    private $human_message = '';
    /**
     * Generated from protobuf field <code>repeated string human_descriptions = 4;</code>
     */
    private $human_descriptions;
    /**
     * Generated from protobuf field <code>.xsuportal.proto.Error.DebugInfo debug_info = 16;</code>
     */
    private $debug_info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $code
     *     @type string $name
     *     @type string $human_message
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $human_descriptions
     *     @type \Xsuportal\Proto\Error\DebugInfo $debug_info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xsuportal\Error::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string human_message = 3;</code>
     * @return string
     */
    public function getHumanMessage()
    {
        return $this->human_message;
    }

    /**
     * Generated from protobuf field <code>string human_message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setHumanMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->human_message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string human_descriptions = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHumanDescriptions()
    {
        return $this->human_descriptions;
    }

    /**
     * Generated from protobuf field <code>repeated string human_descriptions = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHumanDescriptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->human_descriptions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xsuportal.proto.Error.DebugInfo debug_info = 16;</code>
     * @return \Xsuportal\Proto\Error\DebugInfo
     */
    public function getDebugInfo()
    {
        return $this->debug_info;
    }

    /**
     * Generated from protobuf field <code>.xsuportal.proto.Error.DebugInfo debug_info = 16;</code>
     * @param \Xsuportal\Proto\Error\DebugInfo $var
     * @return $this
     */
    public function setDebugInfo($var)
    {
        GPBUtil::checkMessage($var, \Xsuportal\Proto\Error_DebugInfo::class);
        $this->debug_info = $var;

        return $this;
    }

}

