<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/error.proto

namespace Xsuportal\Proto;

if (false) {
    /**
     * This class is deprecated. Use Xsuportal\Proto\Error\DebugInfo instead.
     * @deprecated
     */
    class Error_DebugInfo {}
}
class_exists(Error\DebugInfo::class);
@trigger_error('Xsuportal\Proto\Error_DebugInfo is deprecated and will be removed in the next major release. Use Xsuportal\Proto\Error\DebugInfo instead', E_USER_DEPRECATED);

