<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/admin/clarifications.proto

namespace Xsuportal\Proto\Services\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xsuportal.proto.services.admin.CreateClarificationRequest</code>
 */
class CreateClarificationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string answer = 2;</code>
     */
    private $answer = '';
    /**
     * Generated from protobuf field <code>string question = 3;</code>
     */
    private $question = '';
    /**
     * Generated from protobuf field <code>int64 team_id = 4;</code>
     */
    private $team_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $answer
     *     @type string $question
     *     @type int|string $team_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xsuportal\Services\Admin\Clarifications::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string answer = 2;</code>
     * @return string
     */
    public function getAnswer()
    {
        return $this->answer;
    }

    /**
     * Generated from protobuf field <code>string answer = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAnswer($var)
    {
        GPBUtil::checkString($var, True);
        $this->answer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string question = 3;</code>
     * @return string
     */
    public function getQuestion()
    {
        return $this->question;
    }

    /**
     * Generated from protobuf field <code>string question = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setQuestion($var)
    {
        GPBUtil::checkString($var, True);
        $this->question = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 team_id = 4;</code>
     * @return int|string
     */
    public function getTeamId()
    {
        return $this->team_id;
    }

    /**
     * Generated from protobuf field <code>int64 team_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTeamId($var)
    {
        GPBUtil::checkInt64($var);
        $this->team_id = $var;

        return $this;
    }

}

