<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/resources/contest.proto

namespace Xsuportal\Proto\Resources;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xsuportal.proto.resources.Contest</code>
 */
class Contest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp registration_open_at = 1;</code>
     */
    private $registration_open_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp contest_starts_at = 3;</code>
     */
    private $contest_starts_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp contest_freezes_at = 4;</code>
     */
    private $contest_freezes_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp contest_ends_at = 5;</code>
     */
    private $contest_ends_at = null;
    /**
     * Generated from protobuf field <code>.xsuportal.proto.resources.Contest.Status status = 6;</code>
     */
    private $status = 0;
    /**
     * Generated from protobuf field <code>bool frozen = 7;</code>
     */
    private $frozen = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $registration_open_at
     *     @type \Google\Protobuf\Timestamp $contest_starts_at
     *     @type \Google\Protobuf\Timestamp $contest_freezes_at
     *     @type \Google\Protobuf\Timestamp $contest_ends_at
     *     @type int $status
     *     @type bool $frozen
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xsuportal\Resources\Contest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp registration_open_at = 1;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getRegistrationOpenAt()
    {
        return $this->registration_open_at;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp registration_open_at = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setRegistrationOpenAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->registration_open_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp contest_starts_at = 3;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getContestStartsAt()
    {
        return $this->contest_starts_at;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp contest_starts_at = 3;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setContestStartsAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->contest_starts_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp contest_freezes_at = 4;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getContestFreezesAt()
    {
        return $this->contest_freezes_at;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp contest_freezes_at = 4;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setContestFreezesAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->contest_freezes_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp contest_ends_at = 5;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getContestEndsAt()
    {
        return $this->contest_ends_at;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp contest_ends_at = 5;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setContestEndsAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->contest_ends_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xsuportal.proto.resources.Contest.Status status = 6;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.xsuportal.proto.resources.Contest.Status status = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Xsuportal\Proto\Resources\Contest_Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool frozen = 7;</code>
     * @return bool
     */
    public function getFrozen()
    {
        return $this->frozen;
    }

    /**
     * Generated from protobuf field <code>bool frozen = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setFrozen($var)
    {
        GPBUtil::checkBool($var);
        $this->frozen = $var;

        return $this;
    }

}

