<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/resources/contest.proto

namespace Xsuportal\Proto\Resources;

if (false) {
    /**
     * This class is deprecated. Use Xsuportal\Proto\Resources\Contest\Status instead.
     * @deprecated
     */
    class Contest_Status {}
}
class_exists(Contest\Status::class);
@trigger_error('Xsuportal\Proto\Resources\Contest_Status is deprecated and will be removed in the next major release. Use Xsuportal\Proto\Resources\Contest\Status instead', E_USER_DEPRECATED);

