<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/resources/team.proto

namespace Xsuportal\Proto\Resources;

if (false) {
    /**
     * This class is deprecated. Use Xsuportal\Proto\Resources\Team\StudentStatus instead.
     * @deprecated
     */
    class Team_StudentStatus {}
}
class_exists(Team\StudentStatus::class);
@trigger_error('Xsuportal\Proto\Resources\Team_StudentStatus is deprecated and will be removed in the next major release. Use Xsuportal\Proto\Resources\Team\StudentStatus instead', E_USER_DEPRECATED);

