<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/resources/staff.proto

namespace GPBMetadata\Xsuportal\Resources;

class Staff
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abb010a1f787375706f7274616c2f7265736f75726365732f7374616666" .
            "2e70726f746f1219787375706f7274616c2e70726f746f2e7265736f7572" .
            "63657322290a055374616666120a0a02696418012001280312140a0c6769" .
            "746875625f6c6f67696e180220012809424a5a486769746875622e636f6d" .
            "2f697375636f6e2f697375636f6e31302d66696e616c2f7765626170702f" .
            "676f6c616e672f70726f746f2f787375706f7274616c2f7265736f757263" .
            "6573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

