<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/services/common/me.proto

namespace GPBMetadata\Xsuportal\Services\Common;

class Me
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Xsuportal\Resources\Team::initOnce();
        \GPBMetadata\Xsuportal\Resources\Contestant::initOnce();
        \GPBMetadata\Xsuportal\Resources\Contest::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0abd030a22787375706f7274616c2f73657276696365732f636f6d6d6f6e" .
            "2f6d652e70726f746f121f787375706f7274616c2e70726f746f2e736572" .
            "76696365732e636f6d6d6f6e1a24787375706f7274616c2f7265736f7572" .
            "6365732f636f6e74657374616e742e70726f746f1a21787375706f727461" .
            "6c2f7265736f75726365732f636f6e746573742e70726f746f22d2010a19" .
            "47657443757272656e7453657373696f6e526573706f6e7365122d0a0474" .
            "65616d18012001280b321f2e787375706f7274616c2e70726f746f2e7265" .
            "736f75726365732e5465616d12390a0a636f6e74657374616e7418022001" .
            "280b32252e787375706f7274616c2e70726f746f2e7265736f7572636573" .
            "2e436f6e74657374616e7412330a07636f6e7465737418042001280b3222" .
            "2e787375706f7274616c2e70726f746f2e7265736f75726365732e436f6e" .
            "7465737412160a0e707573685f76617069645f6b65791806200128094250" .
            "5a4e6769746875622e636f6d2f697375636f6e2f697375636f6e31302d66" .
            "696e616c2f7765626170702f676f6c616e672f70726f746f2f787375706f" .
            "7274616c2f73657276696365732f636f6d6d6f6e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

