<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/resources/leaderboard.proto

namespace Xsuportal\Proto\Resources;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>xsuportal.proto.resources.Leaderboard</code>
 */
class Leaderboard extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.resources.Leaderboard.LeaderboardItem teams = 1;</code>
     */
    private $teams;
    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.resources.Leaderboard.LeaderboardItem general_teams = 2;</code>
     */
    private $general_teams;
    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.resources.Leaderboard.LeaderboardItem student_teams = 3;</code>
     */
    private $student_teams;
    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.resources.Leaderboard.LeaderboardItem progresses = 4;</code>
     */
    private $progresses;
    /**
     * Generated from protobuf field <code>.xsuportal.proto.resources.Contest contest = 5;</code>
     */
    private $contest = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem[]|\Google\Protobuf\Internal\RepeatedField $teams
     *     @type \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem[]|\Google\Protobuf\Internal\RepeatedField $general_teams
     *     @type \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem[]|\Google\Protobuf\Internal\RepeatedField $student_teams
     *     @type \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem[]|\Google\Protobuf\Internal\RepeatedField $progresses
     *     @type \Xsuportal\Proto\Resources\Contest $contest
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Xsuportal\Resources\Leaderboard::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.resources.Leaderboard.LeaderboardItem teams = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTeams()
    {
        return $this->teams;
    }

    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.resources.Leaderboard.LeaderboardItem teams = 1;</code>
     * @param \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTeams($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem::class);
        $this->teams = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.resources.Leaderboard.LeaderboardItem general_teams = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGeneralTeams()
    {
        return $this->general_teams;
    }

    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.resources.Leaderboard.LeaderboardItem general_teams = 2;</code>
     * @param \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGeneralTeams($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem::class);
        $this->general_teams = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.resources.Leaderboard.LeaderboardItem student_teams = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStudentTeams()
    {
        return $this->student_teams;
    }

    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.resources.Leaderboard.LeaderboardItem student_teams = 3;</code>
     * @param \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStudentTeams($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem::class);
        $this->student_teams = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.resources.Leaderboard.LeaderboardItem progresses = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProgresses()
    {
        return $this->progresses;
    }

    /**
     * Generated from protobuf field <code>repeated .xsuportal.proto.resources.Leaderboard.LeaderboardItem progresses = 4;</code>
     * @param \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProgresses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Xsuportal\Proto\Resources\Leaderboard\LeaderboardItem::class);
        $this->progresses = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.xsuportal.proto.resources.Contest contest = 5;</code>
     * @return \Xsuportal\Proto\Resources\Contest
     */
    public function getContest()
    {
        return $this->contest;
    }

    /**
     * Generated from protobuf field <code>.xsuportal.proto.resources.Contest contest = 5;</code>
     * @param \Xsuportal\Proto\Resources\Contest $var
     * @return $this
     */
    public function setContest($var)
    {
        GPBUtil::checkMessage($var, \Xsuportal\Proto\Resources\Contest::class);
        $this->contest = $var;

        return $this;
    }

}

