<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xsuportal/resources/notification.proto

namespace Xsuportal\Proto\Resources;

if (false) {
    /**
     * This class is deprecated. Use Xsuportal\Proto\Resources\Notification\ClarificationMessage instead.
     * @deprecated
     */
    class Notification_ClarificationMessage {}
}
class_exists(Notification\ClarificationMessage::class);
@trigger_error('Xsuportal\Proto\Resources\Notification_ClarificationMessage is deprecated and will be removed in the next major release. Use Xsuportal\Proto\Resources\Notification\ClarificationMessage instead', E_USER_DEPRECATED);

